Adding player position column to the existing feature matrix

In [49]:
import numpy as np
import pandas as pd

players = pd.read_csv('players.csv')
feature_matrix = pd.read_csv('feature_matrix.csv')
feature_matrix = feature_matrix.drop(columns = ['Unnamed: 0'], axis = 1)

In [50]:
feature_matrix

,player_id,game_id,season,homeOrAway,goals_1,goals_5,goals_10,goals_20,goals_season,assists_1,...,sh_goals_5,sh_goals_10,sh_goals_20,sh_goals_season,sh_assists_1,sh_assists_5,sh_assists_10,sh_assists_20,sh_assists_season,dfs_points
0,8448208,20,2015,H,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.5
1,8448208,35,2015,A,2.0,NaN,NaN,NaN,2.000000,0.0,...,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,0.000000,3.0
2,8448208,41,2015,A,0.0,NaN,NaN,NaN,1.000000,0.0,...,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,0.000000,8.0
3,8448208,55,2015,H,0.0,NaN,NaN,NaN,0.666667,1.0,...,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,0.000000,29.5
4,8448208,68,2015,H,2.0,NaN,NaN,NaN,1.000000,1.0,...,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,NaN,0.000000,9.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217495,8481813,980,2019,A,0.0,0.0,0.0,0.10,0.106430,0.0,...,0.0,0.0,0.0,0.002217,0.0,0.0,0.0,0.0,0.002217,1.5
217496,8481813,982,2019,A,0.0,0.0,0.0,0.10,0.106195,0.0,...,0.0,0.0,0.0,0.002212,0.0,0.0,0.0,0.0,0.002212,1.5
217497,8481813,1009,2019,H,0.0,0.0,0.0,0.10,0.105960,0.0,...,0.0,0.0,0.0,0.002208,0.0,0.0,0.0,0.0,0.002208,1.5
217498,8481813,1018,2019,A,0.0,0.0,0.0,0.05,0.105727,0.0,...,0.0,0.0,0.0,0.002203,0.0,0.0,0.0,0.0,0.002203,1.5
217499,8481813,1068,2019,H,0.0,0.0,0.0,0.05,0.105495,0.0,...,0.0,0.0,0.0,0.002198,0.0,0.0,0.0,0.0,0.002198,0.0

In [51]:
feature_matrix = feature_matrix.merge(players[['id', 'primaryPositioncode', 'primaryPositionname', 'primaryPositiontype']], how = 'left', left_on = 'player_id', right_on = 'id')

In [52]:
feature_matrix = feature_matrix.drop(columns = ['id'])
feature_matrix.to_csv('feature_matrix_w_position.csv')